server:
  port: 8080

spring:
  application:
    name: boot-jpa-base

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/carmanager
    username: root
    password: 1234

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: false  # p6spy가 대신 로그를 출력하므로 false로 설정

# query logging
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

# swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.bootjpabase.carmanager