server:
  port: 8080

spring:
  application:
    name: boot-jpa-base

# 필요시 secret 파일 사용
#  config:
#    import: application-secret.yml

  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # paging default setting
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort