server:
  port: 8080
spring:
  application:
    name: boot-jpa-base

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/carenation
    username: root
    password: 1234

  profiles:
    default: local

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

# query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    com.p6spy.engine.spy: DEBUG
    com.p6spy.engine.common.P6LogFactory: DEBUG

# swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.bootjpabase.carenation