server:
  port: 8080

spring:
  application:
    name: boot-jpa-base

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/carenation
    username: root
    password: 1234

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

# query logging
logging:
  level:
    com.p6spy: DEBUG
    root: INFO
decorator:
  datasource:
    p6spy:
      enable-logging: true

# swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.bootjpabase.carenation